spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/nodebird
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  logging:
    level:
      org.hibernate.SQL: debug

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB